name: CI/CD for Frappe Meeting App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel
          sudo pip3 install frappe-bench
          bench --version

      - name: Pull Changes
        run: |
          cd apps/meeting-app-ROUGH
          git pull origin main

      - name: Build App
        run: |
          cd apps/meeting-app-ROUGH
          bench build

      - name: Deploy App
        run: |
          cd apps/meeting-app-ROUGH
          bench restart

      - name: Check Deployment Status
        run: |
          # Add any additional checks or tests here
          echo "Deployment successful!"
